# Generated by Django 3.2 on 2021-04-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth_date', models.DateField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
    ]
