# Generated by Django 3.2 on 2021-04-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210423_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default=False, max_length=40, null=True),
        ),
    ]
