# Generated by Django 3.2 on 2021-04-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
